import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactQueryProvider } from "../lib/react-query";
import { Header } from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";

const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased darkmode text-text-primary bg-bg flex flex-col min-h-screen`}
            >
                <ThemeProvider>
                    <Header />
                    <ReactQueryProvider>{children}</ReactQueryProvider>
                    <footer className="p-5">
                        <p className="text-text-secondary font-bold text-center">
                            2023 © Todos os direitos reservados a Cubos Movies
                        </p>
                    </footer>
                </ThemeProvider>
            </body>
        </html>
    );
}
